---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - у пользователя должна быть возможность авторизоваться
  - пользователь может оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность удалять товары из корзины 
  - При перезагркзки страницы,добавленный товар в корзине будет хранится в сессии браузера 
  - Сайт должен быть SPA-приложением, которое не перезагружает страницу
  - На странице товара и в каталоге нужно выводиться название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность удалять товар из корзины
